<?php
/**
 * @package    Eepohs
 * @subpackage Estpay
 */

/**
 * Estpay custom JS and HTML blocks
 *
 * PLEASE READ THIS SOFTWARE LICENSE AGREEMENT ("LICENSE") CAREFULLY
 * BEFORE USING THE SOFTWARE. BY USING THE SOFTWARE, YOU ARE AGREEING
 * TO BE BOUND BY THE TERMS OF THIS LICENSE.
 * IF YOU DO NOT AGREE TO THE TERMS OF THIS LICENSE, DO NOT USE THE SOFTWARE.
 *
 * Copyright (c) $year$, Eepohs OÜ
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @license http://opensource.org/licenses/bsd-license.php
 * @version $version$
 * @author Eepohs OÜ
 * @copyright $year$ Eepohs OÜ http://www.eepohs.com/
 *
 * @package    Eepohs
 * @subpackage Estpay
 * @category   Payment methods
 */
?>
<style type="text/css">
    .eepohs-logo.title-logo{
        height: 14px;
        margin-right: 10px;
        float:left;
    }
    .support-info hr.separator{
        margin: 10px 0px;
    }
    .entry-edit-head.eepohs-payment-method-head{
    }
</style>
<script type="text/javascript">
    //<![CDATA[
    var EEPOHS_SKIN_URL = '<?php echo Mage::getDesign()->getSkinUrl('',array('_area'=>'adminhtml', '_package'=>'default', '_theme'=>'default'));?>';
    function initEepohsPayment() {
        var estpay = new EepohsPayment();
        estpay.addCss( 'entry-edit-head' ,['payment_eepohs_seb-head', 'payment_eepohs_nordea-head', 'payment_eepohs_swedbank-head', 'payment_eepohs_danske-head', 'payment_eepohs_krediidipank-head', 'payment_eepohs_estcard-head', 'payment_eepohs_lhv-head']);
        estpay.addLogoTypes(['payment_eepohs_seb-head', 'payment_eepohs_nordea-head', 'payment_eepohs_swedbank-head', 'payment_eepohs_danske-head', 'payment_eepohs_krediidipank-head', 'payment_eepohs_estcard-head', 'payment_eepohs_lhv-head']);
        estpay.addSupportInformation(['payment_eepohs_seb', 'payment_eepohs_swedbank', 'payment_eepohs_nordea', 'payment_eepohs_krediidipank', 'payment_eepohs_danske', 'payment_eepohs_estcard', 'payment_eepohs_lhv']);
        estpay.setModuleVersion('<?php echo $this->getModuleVersion() ?>');
    }
    //]]>
</script>
<div id="supportInfoTemplate" class="no-display support-info">
    <hr class="separator"/>
    <?php echo $this->__('
        <h3>Eepohs customer support</h3>
        Please contact Eepohs Customer Support if you have questions or problems: <br />
        E-mail: <a href="mailto:support@eepohs.com">support@eepohs.com</a><br />
        Phone: +372 6041104 (Mon-Fri 9.00-17.00 GMT+2)<br /><br />
        Your module name is: Eepohs_Estpay<br />
        Your module version is: ' . $this->getModuleVersion()); ?>
    <div>
        <a href="http://eepohs.com/" title="E-commerce for the masses" target="_blank"><img src="<?php echo $this->getSkinUrl('images/eepohs/estpay/eepohs_logo_x40px.png')?>" alt="Eepohs"/></a>
    </div>
</div>