<?php
/**
 * @package    Eepohs
 * @subpackage EEPay
 */

/**
 * EEPay block template for Swedbank
 *
 * PLEASE READ THIS SOFTWARE LICENSE AGREEMENT ("LICENSE") CAREFULLY
 * BEFORE USING THE SOFTWARE. BY USING THE SOFTWARE, YOU ARE AGREEING
 * TO BE BOUND BY THE TERMS OF THIS LICENSE.
 * IF YOU DO NOT AGREE TO THE TERMS OF THIS LICENSE, DO NOT USE THE SOFTWARE.
 *
 * Full text of this license is available @license
 *
 * @license http://www.eepohs.com/eepohs-commercial-software-license/
 * @licensee $ReleasedTo$
 * @version $version$
 * @author Eepohs OÜ
 * @copyright $year$ Eepohs OÜ http://www.eepohs.com/
 *
 * @package    Eepohs
 * @subpackage EEPay
 * @category   Payment methods
 */
?>
<?php echo $this->getChildHtml('eepay_swedbank_description') ?>
<form id="GatewayForm" name="swedbank" action="<?php echo $this->getGatewayUrl() ?>" method="POST" target="_top">
    <input type="image" src="<?php echo $this->getSkinUrl(sprintf('images/eepohs/eepay/%s_logo_220x31_eng.png', strtolower($this->_gateway)));?>" onclick="this.form.submit()"/>
    <?php foreach($this->getFields() as $key => $value): ?>
	<input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>"/>
    <?php endforeach; ?>
</form>
<?php echo $this->getQuickRedirectScript();?>
