<?php

require_once dirname(__FILE__) . '/../../../../../../../../htdocs/app/code/community/Eepohs/Estpay/Helper/Data.php';

/**
 * Test class for Eepohs_Estpay_Helper_Data.
 * Generated by PHPUnit on 2012-06-05 at 19:06:17.
 */
class Eepohs_Estpay_Helper_DataTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Eepohs_Estpay_Helper_Data
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Eepohs_Estpay_Helper_Data;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Eepohs_Estpay_Helper_Data::calcRef
     * @todo Implement testCalcRef().
     */
    public function testCalcRef()
    {
        $ref = $this->object->calcRef(123);
        $this->assertNotEmpty($ref);
    }

}
