<?php
/**
 * @package    Eepohs
 * @subpackage Estpay
 */
/**
 * Estpay block template for Estcard
 *
 * PLEASE READ THIS SOFTWARE LICENSE AGREEMENT ("LICENSE") CAREFULLY
 * BEFORE USING THE SOFTWARE. BY USING THE SOFTWARE, YOU ARE AGREEING
 * TO BE BOUND BY THE TERMS OF THIS LICENSE.
 * IF YOU DO NOT AGREE TO THE TERMS OF THIS LICENSE, DO NOT USE THE SOFTWARE.
 *
 * Full text of this license is available @license
 *
 * @license http://www.eepohs.com/eepohs-commercial-software-license/
 * @licensee $ReleasedTo$
 * @version $version$
 * @author Eepohs OÜ
 * @copyright $year$ Eepohs OÜ http://www.eepohs.com/
 *
 * @package    Eepohs
 * @subpackage Estpay
 * @category   Payment methods
 */
?>
<div class="payment_estpay_container payment_method_estcard">
    <?php echo $this->getChildHtml('estpay_estcard_description') ?>
    <form id="GatewayForm" name="estcard" action="<?php echo $this->getGatewayUrl() ?>" method="POST" target="_top">
        <img src="<?php echo $this->getSkinUrl('images/eepohs/estpay/estcard_logo_120x31.gif'); ?>" class="payment-gateway-logo estcard_logo"/>
        <?php foreach ($this->getFields() as $key => $value): ?>
            <input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>" />
        <?php endforeach; ?>
        <button class="button" onclick="this.form.submit();"><span><span><?php echo $this->__('Start payment') ?></span></span></button>
    </form>
    <?php echo $this->getQuickRedirectScript(); ?>
</div>
