<?php $gateways = $this->getEnabledGateways() ?>
<?php if ( is_array($gateways) && sizeof($gateways) > 0 ): ?>
    <ul class="estpay-logo-list">
        <?php foreach ( $gateways as
                $gateway ): ?>
            <li class="item">
                <img src="<?php echo $gateway['logo'] ?>" alt="<?php echo $gateway['title'] ?>" title="<?php echo $gateway['title'] ?>"/>
            </li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>
